### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by anonymcoding** [peno64/service.subtitles.localsubtitle#11]
Hi, i m now awared your addons have amazing feature which is dual subtitle function.I want to use it but there is a problem for turkish language maybe others have too.A few turkish characters in the words showing broken.But fixing this issue available in kodi settings to change the subtitle character to the Turkish (iso or windows).Changing it works good with other addons but your addons still keep showing characters like i said.I think your addon not overwriting character type from kodi.Maybe isn't i m not sure but if you understand my point and if you can easily fix this issue i will be very appreciated to you.

**Comment by anonymcoding** [comment]
And it's happening on dual subtitle option no problem with single

**Comment by peno64** [comment]
The dual subtitle feature is accomplished by using the .ssa subtitle format. This format allows to specify multiple subtitles and their position. It also defined the font, it's size and so on. The two provided subtitles are converted to such a .ssa format and it's eventually kodi that displays that subtitle and kodi does supports displaying both. Because also the font, size and so are in that subtitle format that kodi also uses that information instead of the settings in kodi which are used for other subtitle formats like .srt which do not specify the font, size and do on.
So this is somewhat logical.
What subtitle font in kodi do you choose to displays the subtitles correctly when only one subtitle is chosen? Is it the default of do you specify some special values there?

**Comment by anonymcoding** [comment]
Like that picture im just changing character set 
![Screenshot_2022-01-31-18-46-28-818_org xbmc kodi](https://user-images.githubusercontent.com/65981986/151825849-ab1ea78c-b1d6-418d-bec1-90e493aa5794.jpg)

**Comment by anonymcoding** [comment]
> Like that picture im just changing character set ![Screenshot_2022-01-31-18-46-28-818_org xbmc kodi](https://user-images.githubusercontent.com/65981986/151825849-ab1ea78c-b1d6-418d-bec1-90e493aa5794.jpg)

Also tried to enable override ass/ssa subtitles font option for may fix it

**Comment by peno64** [comment]
Will look at it.

**Comment by peno64** [comment]
@muzikherif  
The problem is that an auto detect algorithm is used to detect the encoding of the file and Turkish is not supported by this library. See https://chardet.readthedocs.io/en/latest/supported-encodings.html
And even for supported character sets, there is also a chance that a wrong encoding is returned.
I will have to add an option that you can overrule this encoding

**Comment by anonymcoding** [comment]
Thanks for all your efforts, also for utf 8 based subs there should not be a problem as far as i understand

**Comment by peno64** [comment]
@muzikherif 
There is an update of the addon. In the settings you can now choose the character set.
Auto means that it is auto determined like before and otherwise the chosen character set will be used.
It can happen that the subtitle file cannot be encoded with the chosen subtitle file. You will get a message of that.
The settings can now also be changed when the subtitle addon pops up.

**Comment by anonymcoding** [comment]
@peno64 thanks a lot, i m really appreciated to you.This function really good opinion for practicing language skills

**Comment by anonymcoding** [comment]
Interestingly now utf based turkish subs shows broken by choosing manually to turkish, but at the auto mode works good like before.

**Comment by peno64** [comment]
I guess that is the same when you use the single subtitle feature such that the kodi character set is used.
It does not surprise me. If a specific character set is used then the subtitle file is read as such and utf is a 2 byte character set while the others are single byte character sets.

**Comment by anonymcoding** [comment]
With single subtitle works correct, i do not have a lot of knowledge, therefore im confused

**Comment by peno64** [comment]
Can you provide such a UTF turkish file?

**Comment by anonymcoding** [comment]
[srt.zip](https://github.com/peno64/service.subtitles.localsubtitle/files/8002803/srt.zip)

**Comment by peno64** [comment]
I can add UTF8 as extra character set but it is impossible to treat this file as a Turkish encoded file. It is very strange that kodi also accepts this file when explicitely character set Turkish is chosen.
I will try more this evening.

**Comment by peno64** [comment]
@muzikherif 
I added UTF8 support to the addon. It's the best I can do. You have to choose the correct encoding. I don't fully understand how kodi succeeds in doing this. You choose Turkish encoding in the setting but use an UTF8 encoded files and it is accepted by kodi without a problem. That is not logical. They must somehow overrule this. I may even choose Korean or Chinese character set, with the UTF8 file the character are still displayed correctly. So kodi must do a preprocessing first to determine if this is an UTF file and if so it overrules the chosen character set. 
Kodi is written in C and the library they use probably does this.
Addons are written in Python and in Python, if a specific character set is chosen then it is also expected that the file is in this character set. Can't do much about that.
Note that I recently added the  possibility to go to the addon settings from within the subtitle dialog and as such it is quite easy to change the character set while choosing it. You do get a kodi error message about not being able to load the subtitle after that but I can't do anything about this. The kodi subtitle dialog is limited and expects that a subtitle is chosen after each operation.

**Comment by anonymcoding** [comment]
I can change it from settings manually, no problem, thank you for all your efforts to resolve the issue, it is already enough to see you spearing your time and taking care
