### ISSUE TITLE
Browse for subtitle - Folder empty

### ISSUE THREAD

**Issue by DaisyF8** [peno64/service.subtitles.localsubtitle#8]
I'm browsing to the folder with my subtitles ending with .srt and .ssa but don't see them.

I'm not good at reading code, but does your app only show subtitles if they are named like video.srt or video.ssa ?

Will Real_name_of_movie.srt be shown ?

**Comment by peno64** [comment]
All files endiing with .srt and .ssa are shown.  In fact the following extensions are supported:
.srt|.sub|.ssa|.ass|.idx|.smi|.aqt|.scc|.jss|.ogm|.pjs|.rt|.smi

If browse for subtitle doesn't show your files then this must be a kodi issue because a standard kodi brows for file dialog is used for that:

  subtitlefile = xbmcgui.Dialog().browse(1, __language__(32011), "video", ".srt|.sub|.ssa|.ass|.idx|.smi|.aqt|.scc|.jss|.ogm|.pjs|.rt|.smi", False, False, __subtitlepath__, False)
